### ISSUE TITLE
Estimate gas costs

### ISSUE THREAD

**Issue by ana0** [CirclesUBI/circles-contracts#29]
Come up with a some possible use patterns and estimate gas costs for them

**Comment by JuliointheStudio** [comment]
do we know what parameters does the cost for transaction depends on? I know that when eth is down, things become cheaper. Why is that?

**Comment by ana0** [comment]
Gas is an arbitrary unit that Ethereum uses to measure computational complexity - so like, the more "steps" in any transaction the more gas it takes. Gas also has a price in Ether per unit of gas - this is an open marketplace between people sending transactions and miners. People will pay more in Ether per unit of gas when the network is full to have their transactions mined sooner. And then finally, there's the marketplace for Ether to fiat. So when the fiat price of Ether is low, even if transactions take the same amount of eth, they're cheaper.

For the most part, I'm talking about measuring the first one here, since that's the one we have the most direct control over

**Comment by JuliointheStudio** [comment]
I see. 

Does this mean that through transitive exchange, the number of steps in any given transaction will increase in relation to the steps between 2 people, hence increasing the cost of gas?

Do we have any idea of how much energy goes into creating a block on ethereum today? If we go the mining route (which we definitely should try to avoid if circles grows), it would be useful to let users know how much energy their tokens hold. 

@koeppelmann  said we could use something called Proof of Authority. Because it is centralized, the people who have authority over it can just say yes to the transactions and the cost is supposed to be way cheaper. I do not know the specifics though. 

Have you seen Proof of Cooperation, by the Faircoin peeps? Ihttps://github.com/faircoin/faircoin/blob/master/doc/on-proof-of-cooperation.md

**Comment by ana0** [comment]
Hey!  Realizing I forgot to reply here

>Does this mean that through transitive exchange, the number of steps in any given transaction will increase in relation to the steps between 2 people, hence increasing the cost of gas?

Yep, cost will increase linearly with number of hops

>Do we have any idea of how much energy goes into creating a block on ethereum today?

This is difficult to quantify, since it depends on the hardware being run, and will vary over time as machines turn on and off. True environmental impact is even harder, since that depends on the energy source in the miners location. There are a bunch of estimates you can find, but I've no idea how accurate they are

Proof of Authority and Proof of Cooperation are fundamentally the same thing with different names, insofar as I understand it. Both will use far less energy than a proof of work chain

**Comment by ana0** [comment]
We now have actual gas-cost data, no estimates needed
